### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by nv-yuzho** [bekirbostanci/vda5050_visualizer#1]
Encountered the below error when running with `npm run dev`:
```
(base) ➜  vda5050_visualizer git:(main) npm run dev

> vda_visualizer@0.0.0 dev /home/yu/workspaces/vda5050_visualizer
> vite --host --port 8080

/home/yu/workspaces/vda5050_visualizer/node_modules/vite/bin/vite.js:2
import { performance } from 'node:perf_hooks'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vda_visualizer@0.0.0 dev: `vite --host --port 8080`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vda_visualizer@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by bekirbostanci** [comment]
Can you check your nodejs version 
`npm -v `

**Comment by nv-yuzho** [comment]
I updated it to `10.7.0`, and now I'm seeing the error `Could not resolve "Quill"`. Which version should I use?

**Comment by bekirbostanci** [comment]
I am sharing npm and node version maybe I can also share a docker file if the problem continues
```
➜  ~ node -v             
v18.14.0
➜  ~ npm -v
9.3.1
```

**Comment by nv-yuzho** [comment]
I switched to the same node and npm versions but still had the error `[ERROR] Could not resolve "Quill"`. Could you share the docker file? Thank you.

**Comment by bekirbostanci** [comment]
I added docker file for production and development. Can you test it ?

**Comment by bekirbostanci** [comment]
#2 Please continue to here
